### ISSUE TITLE
Read topic's messages in Operatr

### ISSUE THREAD

**Issue by WigHlod** [operatr-io/community#5]
Hi everyone ! 

We are looking around the Operatr solution for Kafka but we are unable to locate the func about reading message from topics, it's actually available or in the pipe ?

Thank's by advance !
Bye.

**Comment by d-t-w** [comment]
Hello!

Apologies, we've been a bit slow on producing guides/content on how to configure different features.  We expect to have them all online shortly.

If you'll excuse the poor video quality, here's a quick feature overview we made for a partner about topic message inspection with OPERATR:

https://vimeo.com/397080103

You can inspect data on topics, viewing key and message data. You can search for message by key, look in specific partitions, and even produce messages to topics.

We support full AVRO message integration, and with our latest release (# 37) you can view, edit, diff, and verify AVRO schema themselves.

Features that expose data or allow mutation are OFF by default for security reasons, you can turn them on by setting environment variables like:

ALLOW_TOPIC_INSPECT=true    - allow users to see message key/value data
ALLOW_TOPIC_PRODUCE=true  - allow users to produce data to topics
ALLOW_ACL_EDIT=true                - allow users to add/remove ACL
ALLOW_SCHEMA_EDIT=true       - allow uesrs to edit/update AVRO schema

If you need any help just let me know or email us support@operatr.io

**Comment by vcandeau-ep** [comment]
Hi, 

We setup one docker with the last verison of operatr. Operatr is actually working we can view all the metrics, tropic, broker, etc...

But each time we try to view a messages with get :
Request Failed
java.lang.NullPointerException:

This errors occurs either when selecting a deserializer nor not selecting one.

Can you help me to fix this, so we should try your solutions a bit, with us 30 days trial licence.

**Comment by d-t-w** [comment]
Hello, can I ask a couple of quick questions:

1. Are you using release #37 (released in the last 24hrs)?
2. Are you viewing AVRO messages?

There was a regression in release #36 + AVRO that has been resolved.

Otherwise, can you let me know the format of messages you are viewing. Will get this resolved quickly for you.

**Comment by d-t-w** [comment]
On reflection this doesn't sound like the regression in #36.

If possible could you send me the logs from OPERATR regarding the null pointer.

**Comment by vcandeau-ep** [comment]
Hi, 

Actually we are using #37 version. 

And it's JSON Message

Here the logs :
10:13:52.894 ERROR [async-dispatch-5] operatr.kafka.sampler ? Sample error: {:request-id "e60fccfc-a480-4aa9-8320-b4320156f7cc", :key {:field :key, :type "None", :strategy "topic-name", :record-name nil, :text nil, :avro-mode nil, :topic "document.pdf.back.created.rec"}, :value {:field :value, :type "None", :strategy "topic-name", :record-name nil, :text nil, :avro-mode nil, :topic "document.pdf.back.created.rec"}, :val-serde "None", :topic "document.pdf.back.created.rec", :key-serde "None", :key-strategy "topic-name", :val-strategy "topic-name", :timestamp 1586427232612}
java.lang.NullPointerException: null
        at operatr.kafka.serdes$deserialize_record$fn__2792.invoke(serdes.clj:403)
        at clojure.core$update.invokeStatic(core.clj:6196)
        at clojure.core$update.invoke(core.clj:6188)
        at operatr.kafka.serdes$deserialize_record.invokeStatic(serdes.clj:403)
        at operatr.kafka.serdes$deserialize_record.invoke(serdes.clj:400)
        at operatr.kafka.sampler$deserialize.invokeStatic(sampler.clj:46)
        at operatr.kafka.sampler$deserialize.invoke(sampler.clj:41)
        at clojure.core$partial$fn__5843.invoke(core.clj:2638)
        at clojure.core$map$fn__5866.invoke(core.clj:2755)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core$dorun.invokeStatic(core.clj:3133)
        at clojure.core$doall.invokeStatic(core.clj:3148)
        at clojure.core$doall.invoke(core.clj:3148)
        at operatr.kafka.sampler$sample_recent.invokeStatic(sampler.clj:67)
        at operatr.kafka.sampler$sample_recent.invoke(sampler.clj:54)
        at operatr.kafka.sampler$sample$fn__3786.invoke(sampler.clj:172)
        at operatr.kafka.sampler.proxy$java.lang.Object$Callable$7da976d4.call(Unknown Source)
        at com.codahale.metrics.Timer.time(Timer.java:101)
        at operatr.kafka.sampler$sample.invokeStatic(sampler.clj:164)
        at operatr.kafka.sampler$sample.invoke(sampler.clj:162)
        at operatr.server$query_sample.invokeStatic(server.clj:157)
        at operatr.server$query_sample.invoke(server.clj:155)
        at operatr.server$process_request.invokeStatic(server.clj:217)
        at operatr.server$process_request.invoke(server.clj:202)
        at operatr.server$fn__22476$process_fn__22479.invoke(server.clj:298)
        at operatr.server$fn__22476$fn__22591$state_machine__8938__auto____22628$fn__22631.invoke(server.clj:299)
        at operatr.server$fn__22476$fn__22591$state_machine__8938__auto____22628.invoke(server.clj:299)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
        at clojure.core.async$ioc_alts_BANG_$fn__9167.invoke(async.clj:421)
        at clojure.core.async$do_alts$fn__9106$fn__9109.invoke(async.clj:288)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__4519$fn__4520.invoke(channels.clj:95)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at clojure.core.async.impl.concurrent$counted_thread_factory$reify__4422$fn__4423.invoke(concurrent.clj:29)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:834)

The url with the params: /#/data/explore?timestamp=1586428743824&topic=account.created.prod&key-serde=None&key-strategy=topic-name&val-serde=None&val-strategy=topic-name

Trying the recent messages func

**Comment by d-t-w** [comment]
Thank-you so much. This is fixed in release #38 (also now latest) that is now available in Dockerhub.

Please do give it a try and let me know if you experience any more problems.

Thanks for the precise bug ticket!

**Comment by vcandeau-ep** [comment]
Thx for the fast fix answer.

Is there a way to setup the value deserializer at JSON by default ?

It's a bit paintfull to choose it each time

**Comment by d-t-w** [comment]
I'll raise a ticket for default deserializer configuration and include it in our release scheduled for Wednesday next week. I'll let you know when it's available and the details.

Thanks again.

**Comment by vcandeau-ep** [comment]
Thx a lot's :)

**Comment by d-t-w** [comment]
Hello @vcandeau-ep 

Release 40 of Operatr is in github (operatr/operatr:40). 

This release includes the ability to restrict and default serdes for both key and value, e.g.

DEFAULT_KEY_SERDES=JSON
DEFAULT_VALUE_SERDES=JSON

Will cause JSON to be pre-selected when inspecting data.

If you want to remove other serdes you can restrict the set available to select from for both key and value (comma separated):

e.g.

AVAILABLE_KEY_SERDES=JSON,String,Transit / JSON
AVAILABLE_KEY_SERDES=JSON,Integer,Short

Best, Derek.
